
@startuml

|产品层|
start
:获取渠道路由;
|route|
:查询所有符合产品渠道类型的路由策略;
:获取商户分组（根据商户号）;
:获取场景分组（根据场景编码）;
:获取二级商户分组（根据二级商户名称）;
:过滤不符合策略的渠道路由;
:补充渠道详情（根据渠道号）;
:过滤优先级重复的渠道（加权随机）;
note right:分流
:按优先级升序返回渠道路由列表;
|产品层|
stop

'输入：产品渠道、订单金额、交易业务场景、二级商户名称
'输出：所有符合条件的渠道路由
'描述：根据产品渠道、订单金额、交易业务场景、二级商户名称匹配所有符合策略的渠道路由。
@enduml