
@startuml
|cost-center|
start
:消费一条kafka交易信息/
:参数校验;
if(参数校验?) then(不通过)
    note right:订单号、渠道号、机构号、\n产品类型不能为空。
    :设置: 交易状态->失败
    计费标识->未计费
    错误码&描述->参数交易错误;
    else (通过)
endif
partition 订单预处理 {
    :订单重复性校验;
    :订单落库;
}
partition 手续费处理 {
    |agreement|
    :查询协议收费方案;
    |cost-center|
    if(包年 or 包月?)
        :更新订单(实收/后收/免费);
    else
        :计算手续费金额;
        note right
         固定计费: 手续费金额 = 协议计费值
         支付金额低于起费金额: 手续费金额 = 0
         封底金额或封顶金额未配置: 手续费金额 = 交易金额 *　协议计费值
         不到封底金额: 手续费金额 = 封底金额
         超过封顶金额: 手续费金额 = 封顶金额
         其他: 交易计费值 = 手续费金额 *　协议计费值
        end note
        :更新订单状态;
        :redis缓存收费订单信息;
    endif
    if(计费成功？) then(成功)
        :汇总批次处理缓存：机构+柜台+渠道\n（BATCH_CHANNEL_LIST）;
    else (异常)
        : 计费失败，进入清分渠道订单异步计费处理
        dispatch补偿，不限重试，有效期7天。;
    endif
}
stop

'输入：计费订单信息（kafka消息）
'输出：交易信息(订单)落库, 汇总批次缓存交易渠道
'描述：计算手续费，订单落库
@enduml