
@startuml
|cost-center|
start
:根据清分单号查交易基础信息;
|agreement|
    :查询协议收费方案;
    |cost-center|
    if(包年 or 包月?)
        :更新订单(实收/后收/免费);
    else
        :计算手续费金额;
        note right
         固定计费: 手续费金额 = 协议计费值
         支付金额低于起费金额: 手续费金额 = 0
         封底金额或封顶金额未配置: 手续费金额 = 交易金额 *　协议计费值
         不到封底金额: 手续费金额 = 封底金额
         超过封顶金额: 手续费金额 = 封顶金额
         其他: 交易计费值 = 手续费金额 *　协议计费值
        end note
        :更新订单状态;
        :redis缓存收费订单信息;
    endif
    if(计费成功？) then(成功)
    else (异常)
        if(是否已满7天？) then (Y)
            :错误日志落库;
        else (N)
            :间隔30分钟重试;
            detach
        endif
    endif
stop


'输入：计费订单Dispatch任务
'输出：更新交易信息(订单)
'描述：渠道订单入库的失败补偿机制，有效期7天，不限重试次数，重试间隔30分钟。
@enduml