
@startuml
start
:根据批次号、日期查询进行中状态交易信息;
:总成本 = 所有交易成本金额之和;
:更新交易信息状态为成功;
if(该渠道有未结清头寸(INIT)?)
    :总成本累加未结清头寸;
    note right:遇到回溯交易改为减去头寸
    :更新头寸状态为成功;
endif
:成本支付批次汇总落库（INIT);
:成本支付信息落库（INIT);
if(总成本头寸非零?)  then(Y)
    :成本头寸落库（INIT);
else (N)
endif
:成本支付转账批次dispatch命令落库;
stop

'输入：成本支付汇总dispatch任务（批次号）
'输出：成本支付批次汇总、成本支付信息、成本头寸落库。生成成本支付转账dispatch任务。
'描述：按批次号计算总成本，结算历史头寸，记录成本支付信息和新头寸。
@enduml