@startuml
|第一道|
partition partA {
start
floating note left:浮动提示信息\n使用floating note\n left|right:提示内容
if(is has step1) then(step 1)
#pink:step 1;
-[#blue]->
detach
note left
使用detach 将箭头
分离了
endnote
else(进入步骤2)
:step 2<
-[#green,dotted]->//**wangtingwei**//;
endif
}
|第二道|
partition partb {
repeat
:step 3>
-[#DD3322,dashed]->description;
note left
This note is on several
//lines// and can
contain <b>HTML</b>
====
* Calling the method ""step()""
end note
repeatwhile(executeCount<5)
:step 4|
|#blue|第三道|
-[#gray,bold]->加粗测试;
:step 5]
fork
:step 6}
forkagain
#red:step 7;
forkagain
#pink:step 8;
note right
使用fork
forkagain
endfork
并行处理.
endnote
endfork
}
stop
@enduml