
@startuml
|Browser|
start
:输入用户名密码/
:加密请求;
|Monitor-Statiscs|
if (验签) then (N)
    :登录失败;
else (Y)
    |Monitor-Statiscs|
    : 组装请求参数;
    |ams|
    : 校验用户名密码;
    |Monitor-Statiscs|
    if (是一级管理员？) then (Y)
    else (N)
        if (拥有登录权限？) then (Y)
        else (N)
            : 登录失败;
            stop
        endif
    endif
    if (用户状态正常？) then (Y)
        :登录成功;
    else (N)
        :登录失败;
    endif
endif
stop;

'输入：用户名、密码
'输出：登录成功/失败。
'描述：监控平台用户登录。正常状态的ams一级管理员或在监控平台内加过权限的ams用户可以访问监控平台。
@enduml