
@startuml
|Monitor-Message|
start
note right:根据用户编号\n查询用户信息
:输入用户编号/
|Monitor-Message|
if (命中缓存?) then (N)
    |Monitor-Statiscs|
    :查询用户加密信息;
    |ams|
    :查询用户加密信息;
    |Monitor-Message|
    :更新缓存;
    else (y)
endif
|Monitor-Message|
:返回用户加密信息;
stop

'输入：用户编号
'输出：用户加密信息（诸如邮箱、手机号）
'描述：message项目根据AMS用户编号查询邮箱、手机号，用于发送邮件、拨打电话。设置guava缓存。
@enduml