
@startuml
|Browser|
title 线上报表
start
:输入查询条件/
|#white|Monitor-Statiscs|
:组装请求参数
 / es查询语句;
|DPC / ES|
:查询数据;
|Monitor-Statiscs|
:组织返回结果;
|Browser|
:展示报表;
stop

'输入：时间、商户、产品等（各报表不同）
'输出：报表
'描述：在web端查询报表。目前包含商户时长报表、渠道耗时报表、业务异常报表、平均耗时走势图。
@enduml