@startuml
title 认领/分配告警记录
|browser|
start
:选择告警记录处理人/
:填写规则休眠时间/
|monitor-statiscs|
:修改告警记录状态;
:新增告警处理记录;
:缓存规则休眠时间->redis;
note right:休眠时间内规则\n不会重复触发
stop

'输入：告警记录编号、处理人、休眠时间
'输出：告警处理记录入库、休眠时间入redis
'描述：告警记录收件人在微信、邮箱、监控平台网页认领/分配告警记录，告警记录状态修改为处理中，并产生一条告警处理记录。休眠时间缓存进redis，在休眠时间内不会重复触发同样的规则。
@enduml